-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 12:41:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema castores_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `castores_db` ;

-- -----------------------------------------------------
-- Schema castores_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `castores_db` DEFAULT CHARACTER SET latin1 ;
USE `castores_db` ;

-- -----------------------------------------------------
-- Table `castores_db`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `castores_db`.`productos` (
  `id_producto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(100) NOT NULL,
  `descripcion_producto` VARCHAR(255) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT '0',
  `estatus` ENUM('activo', 'inactivo') NULL DEFAULT 'activo',
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `castores_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `castores_db`.`roles` (
  `idRol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `castores_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `castores_db`.`usuarios` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `idRol` INT(11) NOT NULL,
  `estatus` ENUM('activo', 'inactivo') NULL DEFAULT 'activo',
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE,
  INDEX `idRol` (`idRol` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`idRol`)
    REFERENCES `castores_db`.`roles` (`idRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `castores_db`.`movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `castores_db`.`movimientos` (
  `id_movimiento` INT(11) NOT NULL AUTO_INCREMENT,
  `id_producto` INT(11) NULL DEFAULT NULL,
  `id_usuario` INT(11) NULL DEFAULT NULL,
  `tipo_movimiento` ENUM('entrada', 'salida') NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `fecha_hora` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_movimiento`),
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `movimientos_ibfk_1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `castores_db`.`productos` (`id_producto`),
  CONSTRAINT `movimientos_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `castores_db`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 106
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `castores_db`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `castores_db`.`permisos` (
  `idPermiso` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPermiso`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `castores_db`.`rol_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `castores_db`.`rol_permisos` (
  `idRol` INT(11) NOT NULL,
  `idPermiso` INT(11) NOT NULL,
  PRIMARY KEY (`idRol`, `idPermiso`),
  INDEX `idPermiso` (`idPermiso` ASC) VISIBLE,
  CONSTRAINT `rol_permisos_ibfk_1`
    FOREIGN KEY (`idRol`)
    REFERENCES `castores_db`.`roles` (`idRol`)
    ON DELETE CASCADE,
  CONSTRAINT `rol_permisos_ibfk_2`
    FOREIGN KEY (`idPermiso`)
    REFERENCES `castores_db`.`permisos` (`idPermiso`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
